[versions]
accompanistPermissions = "0.32.0"
accompanistSystemuicontroller = "0.32.0"
activity-compose = "1.8.2"
androidx-junit = "1.1.5"
appUpdate = "2.1.0"
biometric = "1.2.0-alpha05"
coilCompose = "2.4.0"
core-ktx = "1.12.0"
coreSplashscreen = "1.0.1"
datastorePreferences = "1.0.0"
desugar_jdk_libs = "2.0.3"
espresso-core = "3.5.1"
google-gson = "2.10.1"
gradle = "8.1.2"
hiltAndroid = "2.48.1"
hiltNavigationCompose = "1.0.0"
junit = "4.13.2"
leakcanaryAndroid = "2.12"
lifecycle-runtime-ktx = "2.6.2"
lifecycleExtensions = "2.2.0"
lifecycleVersion = "2.6.2"
material3 = "1.2.0"
materialIconsExtended = "1.6.2"
navVersion = "2.7.7"
roomVersion = "2.6.1"
runtimeLivedata = "1.5.3"
bom = "2024.02.01"
kotlinBom = "1.9.20"
material3windowsize = "1.1.2"
android-application = "8.1.2"
kotlin-android = "1.9.20"
dagger-hilt-android = "2.48.1"
devtools-ksp = "1.9.22-1.0.16"
zoomable = "0.6.2"
zoomableImageCoil = "0.6.2"
ktlint = "11.6.1"
camerax_version = "1.4.0-alpha01"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
android-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "bom" }
android-kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlinBom" }
compose-ui = "androidx.compose.ui:ui:1.6.0-alpha03"
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleVersion" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleVersion" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleVersion" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleVersion" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3windowsize" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navVersion" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }
app-update = { module = "com.google.android.play:app-update", version.ref = "appUpdate" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdate" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
gson = { module = "com.google.code.gson:gson", version.ref = "google-gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
junit = { module = "junit:junit", version.ref = "junit" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
zoomable = { module = "me.saket.telephoto:zoomable", version.ref = "zoomable" }
zoomable-image-coil = { module = "me.saket.telephoto:zoomable-image-coil", version.ref = "zoomableImageCoil" }
camera-core = { module = "androidx.camera:camera-core", version.ref = "camerax_version" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax_version" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax_version" }
camera-video = { module = "androidx.camera:camera-video", version.ref = "camerax_version" }
camera-mlkit-vision = { module = "androidx.camera:camera-mlkit-vision", version.ref = "camerax_version" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "camerax_version" }
camera-extensions = { module = "androidx.camera:camera-extensions", version.ref = "camerax_version" }


[plugins]
android-application = { id = "com.android.application", version.ref = "android-application" }
android-library = { id = "com.android.library", version.ref = "android-application" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt-android" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtools-ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
